name: Backend Pipeline
on:
  workflow_dispatch:
  push:
    paths:
        - "RealEstateAPI/**"
    branches:
        - main

jobs:
    ci_stage:
        runs-on: ubuntu-latest
        steps:
            - name: check_out
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x  

            - name: Restore dependencies
              working-directory:   RealEstateAPI/RealEstateAPI/
              run: dotnet restore

            - name: Build  
              run: dotnet build --no-restore
              working-directory:   RealEstateAPI/RealEstateAPI/
            
            - name: Test
              run: dotnet test --no-build --verbosity normal
              working-directory:   RealEstateAPI/RealEstateAPI/

            - name: dotnet publish
              run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp    

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                name: .net-app
                path: ${{env.DOTNET_ROOT}}/myapp  

    cd_stage:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: ci_stage
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: .net-app

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}        