name: test reuse workflows
on:
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: test
              uses: AdhamAyad/Learn-Github-Actions/.github/workflows/Triggers.yaml@main  
              with:
                username: "AdhamAyad"      